
let data = [
    {
      id: 11,
      code: "DTC1854",
      fullName: "123 Cảnh",
      address: "Ninh Bình",
      school: "ĐH Hoa Lư",
      mail: "hdc@gmail.com",
      dob: "2000-03-31",
    },
    {
      id: 21,
      code: "DTC123",
      fullName: "Đức 456",
      address: "Hà Nội",
      school: "ĐHQG",
      mail: "hdc@gmail.com",
      dob: "2000-03-31",
    },
    {
      id: 31,
      code: "DTC456",
      fullName: "Hoàng 789",
      address: "Thái Nguyên",
      school: "ĐH Thái Nguyên",
      mail: "hdc@gmail.com",
      dob: "2000-03-31",
    },
    {
      id: 41,
      code: "DTC789",
      fullName: "Đức 456",
      address: "Hà Nội",
      school: "ĐHQG",
      mail: "hdc@gmail.com",
      dob: "2000-03-31",
    },
    {
      id: 51,
      code: "DTC000",
      fullName: "Hoàng 789",
      address: "Thái Nguyên",
      school: "ĐH Thái Nguyên",
      mail: "hdc@gmail.com",
      dob: "2000-03-31",
    },
    {
      id: 313,
      code: "DTC456789",
      fullName: "Hoàng 6789",
      address: "Thái Nguyên",
      school: "ĐH Thái Nguyên",
      mail: "hdc@gmail.com",
      dob: "2000-03-31",
    },
    {
      id: 4,
      code: "DTC789123",
      fullName: "Đức 456",
      address: "Hà Nội",
      school: "ĐHQG",
      mail: "hdc@gmail.com",
      dob: "2000-03-31",
    },
    {
      id: 5,
      code: "DTC000123",
      fullName: "Hoàng 56789",
      address: "Thái Nguyên",
      school: "ĐH Thái Nguyên",
      mail: "hdc@gmail.com",
      dob: "2000-03-31",
    },
]
export default data;
