export const GET_LIST_POST = "GET_LIST_POST";
export const GET_LIST_POST_SUCCESS = "GET_LIST_POST_SUCCESS";

export const DELETE_LIST_POST = "DELETE_LIST_POST";
export const DELETE_LIST_POST_SUCCESS = "DELETE_LIST_POST_SUCCESS";

export const UPDATE_LIST_POST = "UPDATE_LIST_POST";
export const UPDATE_LIST_POST_SUCCESS = "UPDATE_LIST_POST_SUCCESS";

export const CREATE_LIST_POST = "CREATE_LIST_POST";
export const CREATE_LIST_POST_SUCCESS = "CREATE_LIST_POST_SUCCESS";
